// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieCollection.Models;

namespace MovieCollection.Migrations
{
    [DbContext(typeof(MoviesAppContext))]
    [Migration("20220127011327_Initials")]
    partial class Initials
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("MovieCollection.Models.ApplicationInfo", b =>
                {
                    b.Property<int>("ApplicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<string>("Director")
                        .HasColumnType("TEXT");

                    b.Property<string>("Rating")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("ApplicationId");

                    b.ToTable("responses");

                    b.HasData(
                        new
                        {
                            ApplicationId = 1,
                            Category = "Comedy",
                            Director = "Chuck Russell",
                            Rating = "PG-13",
                            Title = "The Mask",
                            Year = 1994
                        },
                        new
                        {
                            ApplicationId = 2,
                            Category = "Comedy",
                            Director = "Adam Shankman",
                            Rating = "PG-13",
                            Title = "The Wedding Planner",
                            Year = 2001
                        },
                        new
                        {
                            ApplicationId = 3,
                            Category = "Family",
                            Director = "Kevin Lima",
                            Rating = "PG",
                            Title = "Enchanted",
                            Year = 2007
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
